# Makefile 模板：需要按你的 ST 标准库路径修改
# 这个文件只作为 VSCode/EIDE 迁移参考，不保证直接编译。

PROJECT = linecar_f103
MCU = cortex-m3

STDLIB = /path/to/STM32F10x_StdPeriph_Lib
CMSIS  = $(STDLIB)/Libraries/CMSIS
SPL    = $(STDLIB)/Libraries/STM32F10x_StdPeriph_Driver

CFLAGS += -mcpu=$(MCU) -mthumb -O0 -g3
CFLAGS += -DUSE_STDPERIPH_DRIVER -DSTM32F10X_MD
CFLAGS += -IUser -IApp -IBSP -IComponents
CFLAGS += -I$(SPL)/inc
CFLAGS += -I$(CMSIS)/CM3/CoreSupport
CFLAGS += -I$(CMSIS)/CM3/DeviceSupport/ST/STM32F10x

SRCS += $(wildcard User/*.c App/*.c BSP/*.c Components/*.c)
SRCS += $(SPL)/src/stm32f10x_gpio.c
SRCS += $(SPL)/src/stm32f10x_rcc.c
SRCS += $(SPL)/src/stm32f10x_tim.c
SRCS += $(SPL)/src/stm32f10x_usart.c
SRCS += $(SPL)/src/misc.c
SRCS += $(CMSIS)/CM3/DeviceSupport/ST/STM32F10x/system_stm32f10x.c

# TODO: 添加 startup_stm32f10x_md.s 和链接脚本
